--створення тимчасової таблиці heroes_info
create table heroes_info(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(30) NOT NULL,
 gender VARCHAR(10),
 eyeColor VARCHAR(40),
 race VARCHAR(40),
 hairColor VARCHAR(40),
  height VARCHAR(40) ,
 publisher  VARCHAR(50),
 skinColor VARCHAR(40),
 alignment VARCHAR(10),
weight INTEGER
);

SELECT * FROM heroes_info;

--копіювання змісту таблиці з csv файлу до таблиці в базі даних pgAdmin4
--SQL hell(psql)
COPY heroes_info
FROM 'C:\Users\ira\JavaProHomeWork\src\main\resources\heroes_information.csv'
DELIMITER ';'
CSV HEADER;

--створення  таблиці heroes
create table heroes(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(30) NOT NULL,
 gender VARCHAR(10),
 eye_color VARCHAR(40),
 race VARCHAR(40),
 hair_color VARCHAR(40),
  height DOUBLE PRECISION ,
 publisher  VARCHAR(50),
 skin_color VARCHAR(40),
 alignment VARCHAR(10),
weight INTEGER
);

--міграція з тимчасової таблиці до heroes
insert into heroes(name, gender, eye_color, race, hair_color, height, publisher, skin_color, alignment, weight)
select name, gender, eyeColor, race, hairColor, to_number(replace(height, ',', '.'), '9999.99'), publisher, skinColor, alignment, weight
from heroes_info;

SELECT * FROM heroes;

--запити
--Середній зріст героїв (виключаючи зріст тих, який нуль або менше)
SELECT AVG(height) AS avg_height FROM heroes WHERE height > 0;

--Ім’я найвищого героя
SELECT name AS hero_with_max_height FROM heroes
WHERE height =( SELECT MAX(height) FROM heroes);

--Ім’я самого важкого героя
SELECT name AS hero_with_max_weight FROM heroes
WHERE weight =( SELECT MAX(weight) FROM heroes);

--Кількість осіб в кожній гендерній групі
SELECT gender, COUNT(*) FROM heroes GROUP BY gender;

--Кількість осіб в кожному угрупуванні (добро / зло / інші)
SELECT alignment, COUNT(*) FROM heroes GROUP BY alignment;

--5 назв самих популярних видавців
SELECT publisher AS top_5_publisher,COUNT(*) FROM heroes
GROUP BY publisher
ORDER BY count desc, publisher asc
LIMIT 5;

--3 назви найрозповсюдженіших кольорів волосся
SELECT hair_color AS top_3_hair_color,COUNT(*) FROM heroes
GROUP BY hair_color
ORDER BY count desc, hair_color asc
LIMIT 3;

--Найрозповсюдженіший колір очей
SELECT eye_color AS the_most_popular_eye_color,COUNT(*) FROM heroes
GROUP BY eye_color
ORDER BY count desc, eye_color asc
LIMIT 1;

--додаткове завдання
--1.створити таблицю publishers
Create TABLE publishers(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(50),
	created_at TIMESTAMP DEFAULT NOW()
);
--2.мігрувати в неї всіх видавців (лише унікальні) з таблиці heroes
insert into publishers(name)
select DISTINCT publisher
from heroes;

--3.додати в heroes поле publisher_id (foreign key на id в publishers)
ALTER TABLE heroes
ADD COLUMN publishers_id INTEGER REFERENCES publishers(id);

SELECT * FROM heroes;

--4.заповнити нову колонку publishers_id в таблиці heroes відповідними значеннями
UPDATE heroes
SET publisher_id = publishers.id FROM publishers WHERE heroes.publisher = publishers.name;

UPDATE heroes
SET publisher_id = 7 WHERE publisher IS NULL;

--5.видалити колонку publisher з героїв
ALTER TABLE heroes
DROP COLUMN publisher;

SELECT * FROM heroes;

--6.переписати запит: 5 назв самих популярних видавців
SELECT id,name AS top_5_publisher_in_update_table
FROM publishers
WHERE id IN (
  SELECT publisher_id
  FROM heroes
  GROUP BY publisher_id
  ORDER BY COUNT(*) DESC
  LIMIT 5
);
