create table homework(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(60)  NOT NULL,
description VARCHAR
);

create table lesson(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(60)  NOT NULL,
updatedAt TIMESTAMP DEFAULT NOW() ,
homework_id INTEGER,
FOREIGN KEY (homework_id) REFERENCES homework(id)
);

create table  schedule(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(60)  NOT NULL,
updatedAt TIMESTAMP DEFAULT NOW()
);

 CREATE TABLE lesson_schedule(
homework_id INTEGER REFERENCES homework(id),
schedule_id INTEGER REFERENCES schedule(id),
 PRIMARY KEY (homework_id, schedule_id)
 );

  select * from homework;
  select * from lesson;
  select * from schedule;
  select * from lesson_schedule;