CREATE TABLE IF NOT EXISTS persons
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) not null,
    uid varchar(40),
    email varchar(255),
    created_at timestamp,
    updated_at timestamp
 );