
CREATE TABLE IF NOT EXISTS transactions(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid varchar(40) UNIQUE,
    from_account varchar(40)  NOT NULL,
	to_account varchar(40)  NOT NULL,
    money numeric(10, 2)  NOT NULL,
	currency varchar(5) NOT NULL,
    created_at timestamp
 );

